### ISSUE TITLE
Hyperparameter selection

### ISSUE THREAD

**Issue by Arlannn1** [pricexu/STAGER#1]
Hello, first thank you for sharing the code! It was so glad to see your works.

Could you give me the hyperparameter settings you used that can reproduce the results in the paper?

Although you have given some hyperparameter search ranges, it is still difficult to reproduce the results. And the results is much lower.

I hope I can get your help and look forward to your reply very sincerely！

**Comment by pricexu** [comment]
Hi! Thanks for your attention to our work and code. We did not save the specific hyper-parameter setting for every dataset but only search the given hyper-parameter range and pick the best one. It is true that the few-shot classes are with very limited training samples so the model performance can be somehow unstable in different runs.
