### ISSUE TITLE
Be confused about the code

### ISSUE THREAD

**Issue by Arlannn1** [pricexu/STAGER#2]
1) In the meta-testing phase, you use both base and novel data. Is this reasonable in few-shot learning? You have used base data in the meta-training phase.Generally speaking, the tasks in the meta-training and meta-testing phases are different, right?
2) What's more, in the test function, why do you still perform 300 epoch of training? In fact, you train the model with the data of base and novel at the same time, and then test it. Is this reasonable? In my opinion, the upper bound of generalized few-shot may be obtained by training the two data together. This is also one of the reasons why I think your experimental results are high.
3) In terms of training times, when the model is trained for 1000 times in meta-train, it will be trained for 3000 times in meta-test.

**Comment by pricexu** [comment]
Hi! For your questions,
1. Our setting is the generalized few-shot learning setting (like an extremely imbalanced learning setting). So in the meta-test phase, the base classes are also used (but the test samples from the base classes will never be used for training).
2. I think maybe you are a little bit confused about the episodic training (and our generalized episodic training). For the meta-test phase, the lower-level learner needs to learn from scratch with the help of the upper-level learner (i.e., meta-learner). Hence, in the meta-test phase, it still includes a training phase.
3. Yes. The meta-training phase's target is the meta-learner, and the meta-test phase's target is the learner. Also, please notice that the learner will be re-initialized (see line 276). So the training in the meta-test phase will not be accumulated.
